version: '2'
services:
    kaigameweb-app:
        image: kaigameweb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://kaigameweb-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=KaiGameWeb
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kaigameweb-mongodb:
        extends:
            file: mongodb.yml
            service: kaigameweb-mongodb
