version: '2'
services:
    kaigameadmin-app:
        image: kaigameadmin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://kaigameadmin-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=KaiGameAdmin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8060:8060
    kaigameadmin-mongodb:
        extends:
            file: mongodb.yml
            service: kaigameadmin-mongodb
