version: '2'
services:
    kaigamegame-app:
        image: kaigamegame
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://kaigamegame-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=KaiGameGame
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    kaigamegame-mongodb:
        extends:
            file: mongodb.yml
            service: kaigamegame-mongodb
